### ISSUE TITLE
Questions:

### ISSUE THREAD

**Issue by owenshen24** [Betoken/betoken#14]
1) Should the InitializeSubcontracts function be automatically called after initializing the GroupFund (aka in the GroupFund constructor)?

**Comment by owenshen24** [comment]
2) To avoid overpaying for Oraclize, wouldn't it be good to transfer everything from the Oraclize contract back into the GroupFund every time a Cycle ends, and then put a small amount back in when a new Cycle starts?

This avoids too many extra funds getting "locked in" inside the OraclizeHandler contract.

**Comment by owenshen24** [comment]
3) EndProposalMakingTime function is super huge (3 for loops!). Can we break it up into smaller chunks, so it's clearer what's happening?

**Comment by ZeframLou** [comment]
1. It's possible but unnecessary. We're using a migration script anyways.
2. Good idea. We can dynamically calculate the fees required for each cycle in endProposalTime(), since they're only dependent on the number of queries, which is just 2 * numOfProposals
3. We can.
