### ISSUE TITLE
Current Kairo staking favors earlier Proposals

### ISSUE THREAD

**Issue by owenshen24** [Betoken/betoken#16]
Because we're taking X% of the current Kairo (and doing the transfer immediately), Proposals you support later on will get less Kairo.

EX: The flat rate to stake is 50% of your Kairo.
I have 100 Kairo.
I support 2 Proposals.
First, I stake 50 Kairo on Proposal 1.
Then I stake 25 Kairo on Proposal 2.
This is inequitable, maybe, and seems bad?

**Comment by ZeframLou** [comment]
@owenshen24 This problem is non-existent. You support a proposal by specifying the amount of ether you want to invest, not the proportion of you Kairo balance. This problem used to exist for staking against proposals, but it's been fixed already.

**Comment by owenshen24** [comment]
Sounds good. I haven't been up to date with the codebase, and these were issues that came up in the simulation, so I brought them up here.
