### ISSUE TITLE
What if *all* proposals are profitable?

### ISSUE THREAD

**Issue by owenshen24** [Betoken/betoken#35]
In this current bullish market, it's conceivable that we'll see cycles where everything goes up.
In our current model, do we just want to mint add'l Kairo and give it to all participants?
Should we care about investments that grew _more_ than other ones?

**Comment by ZeframLou** [comment]
It is conceivable that everything would go up, but even then it's highly unlikely that the supporting side's total stake is more than the opposing side's **entire Kairo balance**. Minting would only occur in extreme edge cases.

It would be good to include the magnitude of profit into the equation.

**Comment by ZeframLou** [comment]
Fixed in the new model
