### ISSUE TITLE
Add error handlers for Oraclize queries

### ISSUE THREAD

**Issue by ZeframLou** [Betoken/betoken#7]

**Comment by owenshen24** [comment]
Looks like Oraclize might just return an empty string when the URL is invalid. Already asked a question on Gitter. I'm wondering if we could just do a simple check to see if the value is still undefined after the query and do something accordingly.

**Comment by owenshen24** [comment]
Oraclize returns "" (the empty string) if the query fails. We should use this as the basis of our error handler.
